In [1]:

from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size = 10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2086, 3616, 9130, 597],
 [2086, 3616, 9130, 8736],
 [2086, 3253, 9130, 8078],
 [4448, 6894, 1214, 8577, 6602],
 [4448, 6894, 1214, 8577, 8987],
 [1631, 2086, 9580, 9130, 90],
 [7109, 6151, 7471, 8577]]

In [8]:
## word Embedding Representation


from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding = 'pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2086 3616 9130  597]
 [   0    0    0    0 2086 3616 9130 8736]
 [   0    0    0    0 2086 3253 9130 8078]
 [   0    0    0 4448 6894 1214 8577 6602]
 [   0    0    0 4448 6894 1214 8577 8987]
 [   0    0    0 1631 2086 9580 9130   90]
 [   0    0    0    0 7109 6151 7471 8577]]


In [11]:
## feature representation
dim=10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_length))
model.compile('adam','mse')


c:\Users\Admin\Desktop\RNN-Projext\venv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step


array([[[-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [ 2.74126418e-02, -6.85242563e-03, -2.86696311e-02,
         -2.38382220e-02,  2.19508298e-02,  2.35450976e-02,
          4.00928892e-02, -4.18894514e-02, -4.462300

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 2086, 3616, 9130,  597], dtype=int32)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [-6.22953102e-03, -2.59487983e-02,  2.71741487e-02,
          1.73886679e-02, -7.68648461e-03,  3.99225466e-02,
          1.64960958e-02, -1.65601820e-03, -2.53946073e-02,
          2.89583690e-02],
        [ 2.74126418e-02, -6.85242563e-03, -2.86696311e-02,
         -2.38382220e-02,  2.19508298e-02,  2.35450976e-02,
          4.00928892e-02, -4.18894514e-02, -4.462300